server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: root
    password: ankan
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
